camera_transform_to_pyb_origin:
  rpy:
  - -130.0
  - 0.0
  - 0.0
  xyz:
  - 0.45
  - -1.2
  - 1.3
dist_threshold: 0.03
drl_horizon: 5
enable_PC: false
max_inference_steps: 5000
robot_voxel_safe_distance: 0.15
voxel_cluster_threshold: 0.5
voxel_size: 0.05
