# config that builds the env as Yifan had it
run:
  load_model: False  
  model_path: ""  
  train:
    num_envs : 16  
    timesteps: 15000000 
    save_freq : 30000
    save_folder: "./models/weights"  
    save_name: "PPO_default"
    ppo_steps: 1024  
    batch_size: 512
    gamma: 0.99  
    tensorboard_folder: "./models/tensorboard_logs"
    custom_policy:
      use: False
      activation_function: "ReLU"  
      layers:
        layer1: 128
        layer2: 128
        value_function:
          layer1: 64
        policy_function:
          layer1: 32
          layer2: 32
          layer3: 16      
  eval:
    max_episodes: -1  
    logging: 1  
    display_delay: 0.00416666666 

env:
  max_steps_per_episode: 1024  
  use_physics_sim: True  # strictly speaking the original code had this at False
  physics_steps_per_env_step: 1
  sim_step: 0.00416666666  
  stat_buffer_size: 25  
  normalize_observations: False
  normalize_rewards: False
  robots:
    - type: "KR16" 
      config:
        name: "kr16_1"
        base_position: [0, 0, 0]
        base_orientation: [0, 0, 0]
        resting_angles: [0, -135, 90, 0, 90, 0]
        control_mode: 0
        xyz_delta: 0.005
        rpy_delta: 0.005
      sensors:
        - type: "LidarSensorKR16"
          config:
            update_steps: 1
            add_to_observation_space: True
            add_to_logging: True
            indicator_buckets: 6
            ray_start: 0.01
            ray_end: 0.3
            num_rays_circle_directions: 5
            num_rays_side: 5
            render: False
            indicator: True
            activated_links: [0, 1, 2]
      goal:
        type: "PositionCollision"
        config:
          normalize_rewards: False
          normalize_observations: False
          add_to_logging: True
          continue_after_success: True
          reward_success: 10
          reward_collision: -5
          reward_distance_mult: -0.01
          dist_threshold_start: 0.2
          dist_threshold_end : 0.01
          dist_threshold_increment_start: 0.01
          dist_threshold_increment_end: 0.001
          dist_threshold_overwrite: "None"

  world:
    type: "KukaShelfExperiment"
    config:
      workspace_boundaries: [-3, 3, -3, 3, 0.0, 3]
      shelves_positions: [[-1.025, -1.25, 0], [-1.025, 1.75, 0]]
      shelves_rotations: [[90, 0, 0], [90, 0, 0]]  # rpy in degrees
      humans_positions: []
      humans_rotations: []
      humans_trajectories: []
      target_pos_override: []
      target_rot_override: []
      start_override: []
      shelf_params:
        rows: 4
        cols: 4
        element_size: 0.5
        shelf_depth: 0.5
        wall_thickness: 0.01
      