# config that builds the env as Yifan had it
run:
  load_model: False  
  model_path: ""  
  train:
    num_envs : 16  
    timesteps: 15000000 
    save_freq : 30000
    save_folder: "./models/weights"  
    save_name: "PPO_default"
    ppo_steps: 1024  
    batch_size: 512
    gamma: 0.99  
    tensorboard_folder: "./models/tensorboard_logs"
    custom_policy:
      use: True
      activation_function: "ReLU"  
      layers:
        layer1: 128
        layer2: 128
        value_function:
          layer1: 64
        policy_function:
          layer1: 32
          layer2: 32
          layer3: 16      
  eval:
    max_episodes: -1  
    logging: 1  

env:
  max_steps_per_episode: 1024  
  use_physics_sim: True  # strictly speaking the original code had this at False
  sim_step: 0.00416666666  
  stat_buffer_size: 25  
  normalize_observations: False
  normalize_rewards: False
  robots:
    robot1:
      type: "UR5" 
      config:
        name: "ur5_1"
        base_position: [0, -0.12, 0.5]
        base_orientation: [0, 0, 0]
        resting_angles: [0, 90, -30, -120, -80, 90]
        control_mode: 0
        xyz_delta: 0.005
        rpy_delta: 0.005
      sensors:
        sensor1:
          type: "LidarSensorUR5"
          config:
            update_steps: 1
            add_to_observation_space: True
            add_to_logging: True
            indicator_buckets: 6
            ray_start: 0
            ray_end: 0.3
            num_rays_circle_directions: 7
            num_rays_side: 7
            render: False
            indicator: True
      goal:
        type: "PositionCollision"
        config:
          normalize_rewards: False
          normalize_observations: False
          add_to_observation_space: True
          add_to_logging: True
          continue_after_success: True
          reward_success: 10
          reward_collision: -10
          reward_distance_mult: -0.01
          dist_threshold_start: 0.2
          dist_threshold_end : 0.01
          dist_threshold_increment_start: 0.01
          dist_threshold_increment_end: 0.001
          dist_threshold_overwrite: "None"

  world:
    type: "RandomObstacle"
    config:
      workspace_boundaries: [-0.4, 0.4, 0.3, 0.7, 0.2, 0.5]
      num_static_obstacles: 3
      num_moving_obstacles: 1
      box_measurements: [0.025, 0.075, 0.025, 0.075, 0.00075, 0.00125]
      sphere_measurements: [0.005, 0.02]
      moving_obstacles_vels: [0.5, 2]
      moving_obstacles_directions: []
      moving_obstacles_trajectory_length: [0.05, 0.75]