# config that builds the env as Yifan had it
run:
  load_model: True  
  model_path: "./models/weights/PPO_obstaclesensor_testyifan/model_240000_steps"  
  train:
    num_envs : 16  
    timesteps: 15000000 
    save_freq : 30000
    save_folder: "./models/weights"  
    save_name: "PPO_obstaclesensor_testyifan"
    recurrent: False
    ppo_steps: 1024  
    batch_size: 512
    gamma: 0.99
    tensorboard_folder: "./models/tensorboard_logs"
    custom_policy:
      use: True
      activation_function: "ReLU"  
      layers:
        - 512
        - 512
        - value_function:
          - 512
          - 512
        - policy_function:
          - 512
          - 512
      lstm:
        lstm_hidden_size: 64
        n_lstm_layers: 1
        shared_lstm: False
        enable_critic_lstm: True

  eval:
    max_episodes: -1  
    logging: 1  
    display_delay: 0.00416666666 
    show_world_aux: True
    show_goal_aux: True
    show_sensor_aux: False
    pybullet_recorder:
      use: False
      save_path: "demo"
      scale: 1

env:
  max_steps_per_episode: 1024  
  stat_buffer_size: 25  
  normalize_observations: False
  normalize_rewards: False
  engine:
    type: "Pybullet"
    use_physics_sim: True
    gravity: [0, 0, -9.8]
    sim_step: 0.00416666666 
    sim_steps_per_env_step: 1 
  robots:
    - type: "UR5" 
      config:
        name: "ur5_1"
        base_position: [0, -0.12, 0.5]
        base_orientation: [0, 0, 0]
        resting_angles: [0, 90, -30, -120, -80, 90]
        control_mode: 2
        xyz_delta: 0.005
        rpy_delta: 0.005
      goal:
        type: "PositionCollision"
        config:
          add_to_logging: True
          continue_after_success: True
          reward_success: 20
          reward_collision: -10
          reward_distance_mult: -0.01
          dist_threshold_start: 0.4
          dist_threshold_end : 0.01
          dist_threshold_increment_start: 0.01
          dist_threshold_increment_end: 0.00025
          dist_threshold_overwrite: 

  world:
    type: "RandomObstacle"
    config:
      workspace_boundaries: [-0.4, 0.4, 0.3, 0.7, 0.2, 0.5]
      num_static_obstacles: 0
      num_moving_obstacles: 0
      box_measurements: [0.025, 0.075, 0.025, 0.075, 0.00075, 0.00125]
      sphere_measurements: [0.005, 0.02]
      moving_obstacles_vels: [0.05, 0.8]
      moving_obstacles_directions: []
      moving_obstacles_trajectory_length: [0.05, 0.75]