# config that builds the env as Yifan had it
run:
  load_model: False
  model_path: "models/weights/PPO_UR5P2/model_14880000_steps.zip"
  train:
    num_envs : 16
    timesteps: 15000000
    save_freq : 30000
    save_folder: "./models/weights"
    save_name: "PPO_Kr120P1"
    recurrent: False
    ppo_steps: 1024
    batch_size: 512
    gamma: 0.99
    tensorboard_folder: "./models/tensorboard_logs"
    custom_policy:
      use: False
      activation_function: "ReLU"
      layers:
        - 128
        - 128
        - value_function:
          - 64
        - policy_function:
          - 32
          - 32
          - 16
      lstm:
        lstm_hidden_size: 512
        n_lstm_layers: 2
        shared_lstm: False
        enable_critic_lstm: True

  eval:
    max_episodes: -1
    logging: 1
    display_delay: 0.00416666666
    show_world_aux: True
    show_goal_aux: True
    show_sensor_aux: False
    pybullet_recorder:
      use: False
      save_path: "demo"
      scale: 1

env:
  max_steps_per_episode: 1024
  stat_buffer_size: 25
  normalize_observations: False
  normalize_rewards: False
  engine:
    type: "Pybullet"
    use_physics_sim: True
    gravity: [ 0, 0, -9.8 ]
    sim_step: 0.00416666666
    sim_steps_per_env_step: 1
  robots:
    - type: "KR120"
      config:
        name: "kr120_1"
        base_position: [ 0, 0, 1.1 ]
        base_orientation: [ 0, 0, 0 ]
        resting_angles: [0, -135, 90, 0, 90, 0]
        control_mode: 2
        xyz_delta: 0.005
        rpy_delta: 0.005
      sensors:
        #- type: "LidarSensorUR5"
        #  config:
        #    update_steps: 1
        #    add_to_observation_space: True
        #    add_to_logging: True
        #    indicator_buckets: 6
        #    ray_start: 0
        #    ray_end: 0.3
        #    ray_setup:
        #      ee_forward: [ 1, 1 ]
        #      wrist3_circle: [ 5, 5 ]
        #      wrist2_circle: [ 5, 5 ]
        #      wrist1_circle: [ 5, 5 ]
        #      upper_arm: [ 5, 5 ]
        #    indicator: True
        - type: "Obstacle"
          config:
            update_steps: 1
            add_to_observation_space: True
            add_to_logging: True
            num_obstacles: 1
            max_distance: 10
            reference_link_id: 7
      goal:
        type: "PositionCollision"
        config:
          add_to_logging: True
          continue_after_success: True
          reward_success: 10
          reward_collision: -5
          reward_distance_mult: -0.01
          dist_threshold_start: 0.2
          dist_threshold_end: 0.02
          dist_threshold_increment_start: 0.005
          dist_threshold_increment_end: 0.001
          dist_threshold_overwrite: "None"

  world:
    type: "RandomBoxes"
    config:
      #workspace_boundaries: [-0.8, 0.8, -0.8, 0.8, 1.1, 1.9]
      workspace_boundaries: [-2, 2, -2, 2, 0.8, 4]
      #workspace_boundaries: [-5, 5, -5, 5, 1.1, 5]
      box_measurements: [0.025, 0.075, 0.025, 0.075, 0.00075, 0.00125]
      max_num_boxes : 6
      obstacle_min_dist: 0.6